[workspace]

members = [
    "ts_compiler",
    # "ts_code_generation",
    "ts_evaluator",
    "ts_lexer",
    "ts_macros",
    "ts_parser",
    "ts_util",
    "ts_trie",
    "ts_symbol",
    "ts_errors",
]